import os,sys
from setuptools import setup


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

msg = f"""



        {bcolors.OKGREEN}This is a normal error generated by this dummy wheel.{bcolors.ENDC}


        OpenCV is available from the OpenCV module, please see https://docs.alliancecan.ca/wiki/OpenCV

        {bcolors.BOLD}{bcolors.WARNING}IMPORTANT{bcolors.ENDC}: the module {bcolors.BOLD}must{bcolors.ENDC} be loaded {bcolors.BOLD}before{bcolors.ENDC} activating your virtual environment.

        1. Deactivate your virtual environment: deactivate
        2. Load the opencv module: module load gcc opencv/x.y.z
        3. Activate your virtual env.: source <env>/bin/activate
        4. And re-run your pip install command.



        """

if __name__ == "__main__":
    # We allow python setup.py sdist to always work to be able to create the sdist
    sdist_mode = len(sys.argv) == 2 and sys.argv[1] == "sdist"
    bdist_mode = len(sys.argv) == 2 and sys.argv[1] == "bdist_wheel"

    if not sdist_mode and not bdist_mode:
        raise SystemExit(msg)

    name = os.environ.get('DUMMY_NAME', 'opencv')
    setup(
        description=f"Dummy {name} wheels to inform users to load the module instead.",
        name=f"opencv-noinstall" if sdist_mode else f"{name}",
        version=f"{os.environ.get('DUMMY_VERSION',9999)}+dummy.computecanada",
        install_requires = [f"opencv-noinstall==9999+dummy.computecanada"] if bdist_mode else [],
    )
