import os,sys
from setuptools import setup


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


if __name__ == "__main__":
    # We allow python setup.py sdist to always work to be able to create the sdist
    sdist_mode = len(sys.argv) == 2 and sys.argv[1] == "sdist"

    if not sdist_mode:
        msg = f"""



        {bcolors.OKGREEN}This is a normal error generated by this dummy wheel.{bcolors.ENDC}


        PyArrow is available from the Arrow module, please see https://docs.alliancecan.ca/wiki/Arrow

        {bcolors.BOLD}{bcolors.WARNING}IMPORTANT{bcolors.ENDC}: the module {bcolors.BOLD}must{bcolors.ENDC} be loaded {bcolors.BOLD}before{bcolors.ENDC} activating your virtual environment.

        1. Deactivate your virtual environment : deactivate
        2. Load the Arrow module : module load gcc arrow/x.y.z
        3. Activate your virtual env. : source <env>/bin/activate
        4. And re-run your pip install command.



        """

        raise SystemExit(msg)

    setup(
        description="Dummy PyArrow wheels to inform users to load the module instead.",
        name="pyarrow",
        version=f"{os.environ.get('PYARROW_DUMMY_VERSION',9999)}+dummy.computecanada",
    )
