MODULE_BUILD_DEPS='cmake'
MODULE_RUNTIME_DEPS='rdkit/2024.03.5'
PYTHON_DEPS='scikit-build-core>=0.10.7'
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PYTHON_IMPORT_NAME=$PACKAGE
PACKAGE_FOLDER_NAME=$PACKAGE
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/google-deepmind/alphafold3.git"
PACKAGE_DOWNLOAD_CMD="git clone --recursive $PACKAGE_DOWNLOAD_ARGUMENT --branch v${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf $PACKAGE_DOWNLOAD_NAME $PACKAGE_FOLDER_NAME"
PYTHON_VERSION='python/3.11 python/3.12'
PRE_BUILD_COMMANDS="sed -i -e 's/3.0.0/${VERSION}/' pyproject.toml"
