PYTHON_VERSIONS="python/3.7"
PYTHON_DEPS="biopython"
PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/Magdoll/cDNA_Cupcake/archive/v${VERSION}.tar.gz"
PACKAGE_DOWNLOAD_NAME="v${VERSION}.tar.gz"
PACKAGE_FOLDER_NAME="cDNA_Cupcake-${VERSION}"
