MODULE_BUILD_DEPS="gcc suitesparse fftw imkl"
PRE_BUILD_COMMANDS='
export CVXOPT_LAPACK_LIB=mkl_rt; 
export CVXOPT_BLAS_LIB=mkl_rt; 
export CVXOPT_BLAS_LIB_DIR=$MKLROOT/lib; 
export CVXOPT_SUITESPARSE_LIB_DIR=$EBROOTSUITESPARSE/lib; 
export CVXOPT_SUITESPARSE_INC_DIR=$EBROOTSUITESPARSE/include/suitesparse; 
export CVXOPT_BUILD_FFTW=1; 
export CVXOPT_FFTW_LIB_DIR=$EBROOTFFTW/lib; 
export CVXOPT_FFTW_INC_DIR=$EBROOTFFTW/include; 
export CVXOPT_BUILD_GLPK=1;
' 

