PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/deepseek-ai/DeepGEMM.git"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="git clone --depth 1 --recursive --shallow-submodules $PACKAGE_DOWNLOAD_ARGUMENT --branch v${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf ${PACKAGE}-${VERSION}.tar.gz $PACKAGE_FOLDER_NAME"
MODULE_BUILD_DEPS='cuda/12.9'
PRE_BUILD_COMMANDS='
	export TORCH_CUDA_ARCH_LIST="8.0;9.0;10.0+PTX";
	export DG_USE_LOCAL_VERSION=0;
	export DG_FORCE_BUILD=1;
'
PYTHON_DEPS="torch${TORCH_VERSION:+==$TORCH_VERSION}"
