MODULE_RUNTIME_DEPS='fann/2.2.0'
PRE_BUILD_COMMANDS="export PREFIX=\$EBROOTFANN && sed -i 's/1.1.2/$VERSION/' setup.py"
PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/FutureLinkCorporation/fann2"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="git clone $PACKAGE_DOWNLOAD_ARGUMENT --branch ${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf ${PACKAGE}-${VERSION}.tar.gz $PACKAGE_FOLDER_NAME"
