PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/mitsuba-renderer/mitsuba3.git"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="git clone --recursive $PACKAGE_DOWNLOAD_ARGUMENT --branch v${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf ${PACKAGE}-${VERSION}.tar.gz $PACKAGE_FOLDER_NAME"
MODULE_BUILD_DEPS='cmake python-build-bundle cuda llvm'
PYTHON_DEPS='drjit'
PRE_BUILD_COMMANDS='
	export CMAKE_BUILD_PARALLEL_LEVEL=5;
'
PYTHON_IMPORT_NAME='mitsuba'
RPATH_TO_ADD="'\$ORIGIN/..:\$ORIGIN/../../drjit'"
