PYTHON_DEPS=" scipy scikit-learn mdtraj pandas cython<0.28 cvxopt nose tables"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="wget https://github.com/msmbuilder/msmbuilder/archive/refs/tags/3.8.0.tar.gz"
PACKAGE_DOWNLOAD_NAME="3.8.0.tar.gz"
PACKAGE_FOLDER_NAME="msmbuilder-3.8.0"
