MODULE_BUILD_DEPS="hdf5-mpi netcdf-mpi"
MODULE_RUNTIME_DEPS="gcc openmpi mpi4py"
PRE_DOWNLOAD_COMMANDS='export HDF5_DIR=$EBROOTHDF5; export NETCDF4_DIR=$EBROOTNETCDF'
RPATH_TO_ADD='$EBROOTOPENMPI/lib'

