PYTHON_DEPS="pybind11-stubgen netgen-occt-devel"

PACKAGE_FOLDER_NAME="$PACKAGE"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/NGSolve/netgen.git"
PACKAGE_DOWNLOAD_CMD="git clone --recursive $PACKAGE_DOWNLOAD_ARGUMENT --branch v${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf $PACKAGE_DOWNLOAD_NAME $PACKAGE_FOLDER_NAME"

PATCHES="netgen_mesher.patch"

