MODULE_BUILD_DEPS="cmake/3.12.3 cuda/10 opencv/4.1.0 protobuf/3.7.1 boost/1.68.0"
PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/NVIDIA/DALI"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="git clone --recursive $PACKAGE_DOWNLOAD_ARGUMENT --branch v$VERSION $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf ${PACKAGE}-${VERSION}.tar.gz $PACKAGE_FOLDER_NAME"
PRE_BUILD_COMMANDS="mkdir build && cd build && cmake -DCMAKE_SKIP_RPATH=ON -DBUILD_NVJPEG=OFF -DCMAKE_PREFIX_PATH=$EBROOTPROTOBUF -DProtobuf_INCLUDE_DIRS=$EBROOTPROTOBUF/include -DProtobuf_LIBRARIES=$EBROOTPROTOBUF/lib64 -DProtobuf_LIBRARY=$EBROOTPROTOBUF/lib64/libprotobuf.so ..
 && make -j 16 && cd dali/python "
RPATH_TO_ADD="\$ORIGIN:\ORIGIN/.."  # Force origin. Equivalent to use `--add_origin`.

