MODULE_BUILD_DEPS="postgresql"
PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/psycopg/psycopg.git"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="git clone --jobs 16 --depth 1 --recursive $PACKAGE_DOWNLOAD_ARGUMENT --branch ${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf ${PACKAGE}-${VERSION}.tar.gz $PACKAGE_FOLDER_NAME"
PRE_BUILD_COMMANDS="
	python ./tools/ci/copy_to_binary.py && cd psycopg_binary;
"
PYTHON_DEPS="psycopg==$VERSION"
TEST_COMMAND="python -c 'import psycopg, psycopg_binary'"
