PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/nanoporetech/pyspoa"
PACKAGE_DOWNLOAD_NAME="$PACKAGE-$VERSION.tar.gz"
PACKAGE_DOWNLOAD_METHOD="Git"
PACKAGE_DOWNLOAD_CMD="git clone --recursive $PACKAGE_DOWNLOAD_ARGUMENT --branch v${VERSION:?version required} $PACKAGE_FOLDER_NAME"
POST_DOWNLOAD_COMMANDS="tar -zcf ${PACKAGE}-${VERSION}.tar.gz $PACKAGE_FOLDER_NAME"
PRE_BUILD_COMMANDS="sed -i 's/cmake==3.18.4/cmake/' setup.py && make build"
MODULE_BUILD_DEPS="boost"
PYTHON_DEPS="cmake"
