PACKAGE_DOWNLOAD_ARGUMENT="https://github.com/pytorch/tensordict/archive/refs/tags/v${VERSION:?version required}.tar.gz"
PYTHON_DEPS="torch${TORCH_VERSION:+==$TORCH_VERSION}"
PRE_DOWNLOAD_COMMANDS='export SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION;'
PRE_BUILD_COMMANDS='export SETUPTOOLS_SCM_PRETEND_VERSION=$VERSION;'
