MODULE_BUILD_DEPS="gcc/13 tiledb flexiblas"
PRE_BUILD_COMMANDS='export TILEDB_PATH=$EBROOTTILEDB; export CMAKE_ARGS="-DTILEDB_VS_PYTHON=ON -DBUILD_TESTS=OFF";'
MODULE_RUNTIME_DEPS='arrow'
PYTHON_IMPORT_NAME='tiledb.vector_search'

